### ISSUE TITLE
Decrypting files on linux

### ISSUE THREAD

**Issue by uperetz** [jeanpaulrichter/nppcrypt#1]
Hi NPP crypt team,

I'm trying to see if I can use an existing tool to decrypt an nppcrypted file on Debian. So far I failed using mcrypt (here I can actuallyset the algorithm and mode), scrypt and bcrypt, removing the header and newlines. what do you I need to do to make this works? Thanks.

**Comment by jeanpaulrichter** [comment]
sorry, but i found no good way of doing this on linux. openssl i.e. uses weird custom key derivation and i found no tool that provides enough options. maybe i will create a commandline version of nppcrypt in the future for both windows and linux, but atm your best option is wine: as far as i could see notepad++ plus nppcrypt does work more or less fine.

**Comment by uperetz** [comment]
Thanks for the reply and the effort. I for one would very much like a CMD
tool (standalone?), but I'll stick to wine for now.

**Comment by jeanpaulrichter** [comment]
@uperetz when you find time please try to compile the linux cmd tool included in 1.0.1.5a. it's still a bit experimental, but it might just work :)

**Comment by uperetz** [comment]
Tested on Debian Stretch x64:

    You forgot to "#include " - I put it in src/crypt.h, but let me know if there is a more proper place. std::pow won't compile otherwise.
    I suggest in your README to send Linux users to the bottom for the make instruction (so it's clear they need to clone and make release).
    Consider a make install/make install global/local that copies the bin file to the global/local bin (sudo for global needed).
    Consider shortening the action: -en,-de. Also you could by default determine if the header is one made by you (nppcrypt) and decrypt automatically or encrypt otherwise.

These are all suggestions (except 1), but bottom line - works great so far! Nice works and a big thanks. This issue should be closed.

**Comment by uperetz** [comment]
Tested on Debian Stretch x64:

    You forgot to "#include " - I put it in src/crypt.h, but let me know if there is a more proper place. std::pow won't compile otherwise.
    I suggest in your README to send Linux users to the bottom for the make instruction (so it's clear they need to clone and make release).
    Consider a make install/make install global/local that copies the bin file to the global/local bin (sudo for global needed).
    Consider shortening the action: -en,-de. Also you could by default determine if the header is one made by you (nppcrypt) and decrypt automatically or encrypt otherwise.

These are all suggestions (except 1), but bottom line - works great so far! Nice works and a big thanks. This issue should be closed.

**Comment by jeanpaulrichter** [comment]
thank you for testing. the suggestions seem good to me, i will include them as soon as possible.
