### ISSUE TITLE
Add possibilities (IV & password encoding)

### ISSUE THREAD

**Issue by Hellago** [jeanpaulrichter/nppcrypt#11]
Hello,
Would it be possible to add :
- an input field to manually set the initialisation vector,
- a radio button to select the encoding of the password (UTF-8, Base64, Hex...),
- a radio button to select the encoding of the IV (if the IV is manually set) (UTF-8, Base64, Hex...),
- a radio button to select the kind of password completion, if not to the right length (for AES) : 1) fill with zeros, 2) fill with NUL chars, 3) do not fill (and get error message if incorrect), 4) ...

Thank you very much for your contribution.

**Comment by jeanpaulrichter** [comment]
@Hellago  hi,
these suggestions seem all pretty reasonable to me. potentially the ui could get even more cluttered but it needs a bit of an overhaul anyway. to be honest atm i just don't find time to work on nppcrypt so don't expect an update in the very near future, but i will keep this in mind!

**Comment by jeanpaulrichter** [comment]
most of this stuff will be possible in 1016.

**Comment by Hellago** [comment]
Thank you !
