### ISSUE TITLE
integrity check failed

### ISSUE THREAD

**Issue by xiaotan828** [jeanpaulrichter/nppcrypt#12]
When I try to decrypt, it says like that, I cannot decrypt.  That's really bad, I need my data.

**Comment by xiaotan828** [comment]
By the way the data includes Chinese character, is that the reason it crashed down?

**Comment by jeanpaulrichter** [comment]
@xiaotan828 no, chinese characters do not cause problems. the simplest reason why decryption fails is that the password is wrong. please make sure you didn't accidentally press shiftlock or something. also make sure you select all of the encrypted data. i know your situation is extremly frustrating, but it is simply impossible with very limited information from afar to guess what the problem might be. i certainly do not know of any bug that makes decryption impossible. if the problem persists, please post file encoding, encryption options, what exactly you did etc.

**Comment by xiaotan828** [comment]
Thank you very much, problem solved. My bad.
