### ISSUE TITLE
Decrypting older encryptions from nppcrypt doesn't work

### ISSUE THREAD

**Issue by GreatestFool** [jeanpaulrichter/nppcrypt#13]
Not really sure what would fix it save for just brute forcing it at this point as I'm not really _that_ good at code and such. I know the key however, but the newer versions of nppcrypt are apparently incompatible with older versions and I've been unable to fix it myself even on various older versions of NP++. I either get an
> Invalid cipher.

or an
> Input is empty.

Depending on which version of NP++ I'm using. On 5.6.4, 'Input is empty' is the message I get, an on newer ones like 6.4+ or 7+ I simply get an Invalid cipher message. On version 5 and such I also have to fill in Salt and Random iv value manually, but it doesn't help.

I don't think this is a problem, as the actual key is not included: 
`<nppcrypt version="101">
<encryption cipher="aes256" mode="cbc" encoding="base16" />
<random iv="FDrFAJ/ohM3RJd4ypAfuaw==" salt="f+DAeBbbccz19Yq8HmrvIQ==" />
<key algorithm="pbkdf2" hash="md5" iterations="1000" />
</nppcrypt>`

On a newer version, this is what it looks like as you know:
`<nppcrypt version="1015">
<encryption cipher="cast256" mode="cbc" encoding="base16" />
<random iv="3VjG3mLKc4KuBeoOBgrvSQ==" salt="kyIiK9V+F8OQ52Np40zIJg==" />
<key algorithm="pbkdf2" hash="md5" iterations="1000" />
</nppcrypt>`

Not sure if you can help, or if you're willing, but am not sure where else to message you. If you can help, I'd greatly appreciate it. Sorry if this is annoying.

**Comment by Tmp341** [comment]
I just use old version (1.0.1.0 for <nppcrypt version="101"> etc), decrypt them, then return back to new version, and encrpyt them again.

**Comment by Tmp341** [comment]
I've backed it up before. Let me check it again.

**Comment by GreatestFool** [comment]
Thank you! Seriously, you're an angel. I managed to decrypt it. Again, thank you for the help.

**Comment by jeanpaulrichter** [comment]
@GreatestFool i'm very late but: thank you very much @Tmp341 for resolving this problem. for the last few months i was so busy with other things that i failed to maintain this project at all (i know how much it sucks if you have a problem like this and nobody responds...). i hope that i now find the time to at least finish the latest version that was more or less done when i stopped working on this. and i will upload all older versions to help with similar problems...
