### ISSUE TITLE
NPPcrypt in 64 bit Notepad++ v7.6.1 not working

### ISSUE THREAD

**Issue by tvrhossain** [jeanpaulrichter/nppcrypt#15]
I installed NPPcrypt in 64 bit Notepad++ v7.6.1, its NOT working, nothing happens when I press encrypt button. There's a changelog file for notepade, the nppcrypt works only for that !! how come !!

**Comment by Tmp341** [comment]
Dumb question i know, but have you selected all the text you would like to encrypt?

**Comment by jeanpaulrichter** [comment]
please add more details about your problem. what exactly are you trying to do? Like Tmp341 said: have you selected the text you want to encrypt? (btw: i will add a short info message in the next version if no text is selected to make it easier for new users) . "There's a changelog file for notepade, the nppcrypt works only for that" -> sorry but i don't understand what you mean by that.
