### ISSUE TITLE
v1.0.1.6 binaries missing

### ISSUE THREAD

**Issue by nikusoft** [jeanpaulrichter/nppcrypt#16]
Hi there,
Many thanks for making nppcrypt! Love it!
I couldn't find this link working.
https://github.com/jeanpaulrichter/nppcrypt/releases/download/1.0.1.6/nppcrypt_1.0.1.6_x64.zip
Couldn't download either x86 or x64 versions of nppcrypt-1.0.1.6.
In the releases tab, only thing I see is - 1.0.1.5

Thanks,
Nirav

**Comment by Tmp341** [comment]
Their MD5 hashes are missing, so im guessing they are not builded yet.

**Comment by molyjohn** [comment]
Hi
Thanks for creating nppcrypt.  Being paranoid I use two packages to encrypt my bulging password database seperately;one of them is nppcrypt. I upgraded Npp today and went to reinstall nppcrypt as a plugin and found the link to the windows binary unavailable. I would be grateful if you could please make the likn available again. 
Thank you again for a great utility

**Comment by jeanpaulrichter** [comment]
@molyjohn sry for answering this late (again). please check the readme.md for a list of current and older versions. the links should be working now.
