### ISSUE TITLE
When already existing nppcrypt files are changed and saved, auth settings get lost

### ISSUE THREAD

**Issue by dinkumoil** [jeanpaulrichter/nppcrypt#18]
# Description
When already existing _nppcrypt_ files (automatic encoding when saved, automatic decoding when loaded) are changed and saved, a dialog box pops up where the user can select to change the encryption of the file. If the user declines that, the settings in register _auth_ of the _Encrypt_ dialog get lost.

# Applies to
NppCrypt v1.0.1.6 BETA (2019/02/21)

**Comment by jeanpaulrichter** [comment]
thanks, i was able to verify this. will look into it tomorrow :)

**Comment by jeanpaulrichter** [comment]
should be fixed

**Comment by dinkumoil** [comment]
Thank you!
