### ISSUE TITLE
Broken build on Linux

### ISSUE THREAD

**Issue by uperetz** [jeanpaulrichter/nppcrypt#19]
Tested only on Ubuntu, but I think this is relevant to many flavors:
1. `cmdline.o` (at least, maybe others) needs to link against functions in `crypt_help.cpp`, which is never compiled. My fix:
    a. In the Makefile add `src/crypt_help.cpp` as second item in `MAIN_SRC` list.
2. Not sure about `LDFLAGS`, but the link against `cryptopp` does not work, and does not seem right even if it was created where it should. By default you create it in `src/cryptopp`, so I left it there but changed the Makefile to:
   a. `LDFLAGS := -lstdc++ -Lsrc/cryptopp -lcryptopp`
   b. You may want to create it in `bin/cryptopp` as you meant, and then you just need to change the -L flag.
3. `crypt.cpp` builds against cryptopp files, but `#define`s are not consistent with those of files compiled in cryptopp - this breaks the build. My fix:
   a. Add `#include cryptopp/config.h` in `crypt.cpp`, before all cryptopp includes.
   b. Add a special recipe below the `src/%.cpp` dependencies, just for crypt.o:
```
       $(OBJDIR)/$(SUBDIR)/crypt.o: src/crypt.cpp 
           $(CXX) $(CXXFLAGS) -DCRYPTOPP_DISABLE_ASM -DCRYPTOPP_DISABLE_MIXED_ASM -I /src/cli11 -c -o $@ $<
```
4. You have `-I /src/cli11` in the `cpp` recipes. I thought `-I` was relative, so, maybe `src/cli11` was meant? Removing seems like it would be OK.
   
Unimportant stuff, you may want to add  to .gitignore the following:
```
 *.o
adhoc.cpp
cryptest.exe
libcryptopp.a
```

Thanks for all your amazing work!
PS:
The program was amazing, and since I last updated has become even more so!

**Comment by jeanpaulrichter** [comment]
thank you for your kind words and especially for your fixes. to be honest I kind of neglected the cli version with the last updates. i will look it over and incorporate the your fix in the next few days.
