### ISSUE TITLE
(05/0125) Preferences file corrupted.

### ISSUE THREAD

**Issue by Xepherxv** [jeanpaulrichter/nppcrypt#2]
every time i open notepad++ i get this error for nppcrypt, its annoying 
![image](https://user-images.githubusercontent.com/4986859/27064120-cf67595a-4fc3-11e7-930f-d0ae8aaf5f3d.png)

**Comment by jeanpaulrichter** [comment]
could you please try the new test version of 1.0.1.4 (see readme) and tell me if this is fixed?

**Comment by Xepherxv** [comment]
seems like it works, will let you know if it comes up again, thank you very much <3

**Comment by jeanpaulrichter** [comment]
thanks for testing! btw: if you plan to use the testversion, please download v1014b (see readme). there was a stupid bug introduced in the migration to cryptopp 5.6.5 (my fault), that may corrupt encryptions with base64 encoding and windows line endings :/

**Comment by NoMoreFood** [comment]
I can confirm this addressed the issue for me as well.
