### ISSUE TITLE
Integrity check failed

### ISSUE THREAD

**Issue by hcaandersen** [jeanpaulrichter/nppcrypt#20]
I'm getting an 'Integrity check failed' error while opening an encrypted file (.nppcrypt).  It's a file that I've edited without problems dozens of time over the period of about a year.  Suddenly last week I started getting this error.  I haven't changed the password.  I've tried decrypting restored backups from times prior to the problem appearing - versions that I know used to open successfully - and they give the same error, so at the moment I can't access my data at all.

Have you got any idea why this might be happening?

**Comment by jeanpaulrichter** [comment]
Sorry for answering this late. I know your situation is terrible, but without much more information I am not sure I can help you. Are you sure you used the same version for encryption as for decryption?

**Comment by hcaandersen** [comment]
Oh no, please don't stress about this.  I'm just grateful that you've chosen to spend the time building the plug-in.  Anyway, it's not so bad because the content of file isn't that important, though it would be nice to get it back.

Before I try to provide diagnostics, can I ask you if you can think of anything that could cause a file that could be opened about three weeks to give the integrity error now.  I've tried with backup copies - versions of the file that I know I used to be able to open - and they also give the same error.  I can only conclude that something other than the files has changed.  I may have installed an update, so that could be the cause.  Are you aware of anything in your code that has changed that can cause this problem?

I think I first started using the plug-in at the middle of last year, so perhaps I can roll back to the version that was current at that time.  Are old versions available somewhere?

**Comment by jeanpaulrichter** [comment]
the only reason that i can think of is that maybe the plugin was updated by the plugin manager to 1016 without you noticing. the strange thing is that normally you should be notified that the header version of your file is incompatible. anyway it is certainly worth a try to downgrade to 1015. you can find older versions listed in the readme of this repository or 1015 directly here: https://github.com/jeanpaulrichter/nppcrypt/releases/download/1.0.1.5/nppcrypt_1.0.1.5_x86.zip or https://github.com/jeanpaulrichter/nppcrypt/releases/download/1.0.1.5/nppcrypt_1.0.1.5_x64.zip

**Comment by hcaandersen** [comment]
Thank you very much for your reply.  I have no idea why, but this morning the file opened without any problems.  I hadn't installed the old versions that you kindly provided yet, so that wasn't the reason - it just suddenly worked.  Anyway, if it happens again, I'll try those and let you know if that helped.  Thank you again!
