### ISSUE TITLE
Encoding option "ascii" permanently disabled

### ISSUE THREAD

**Issue by cubinator** [jeanpaulrichter/nppcrypt#4]
The option to encode the encrypted data to ascii and the option to decrypt from ascii is permanently disabled in v1.0.1.3 regardless of all other options. In v1.0.1.2 the option was working.

I'm using Notepad++ v6.9 x86 on Windows 8.1 x64 with NppCrypt v1.0.1.3. (Notepad x86, because x64 hasn't yet got all plugins I need)

**Comment by jeanpaulrichter** [comment]
hi, i fixed this in the latest 1.0.1.4c test version (see readme).
