### ISSUE TITLE
If N > 19, header invalid

### ISSUE THREAD

**Issue by coldChili** [jeanpaulrichter/nppcrypt#5]
If N is set bigger than 19, it is than recorded in scientific notation in the header and fail when try to read it afterwards.
nppcrypt Can't parse this header but if i change 1.04858e+06 to 1048576, problem's gone. (same with v. 1013)
nppcrypt version="1014"
encryption cipher="rijndael256" mode="gcm" encoding="base64" tag="1gJcnQJy4JDGiE6+4daR6g=="
random iv="5GDrL1kgNw3uWSgQ9zUnJQ==" salt="42oDiIjyxxUSgsWZUHleGu+6NwnOtjTjzkBBa3Eccu0=" 
key algorithm="scrypt" N="1.04858e+06" r="16" p="4"
nppcrypt
(I had to edit the header, otherwise wont get posted)
thanks for this nice plugin

**Comment by jeanpaulrichter** [comment]
thx for reporting. will be fixed in 1014 (see readme: nppcryptv1014d.x64.zip)
