### ISSUE TITLE
Invalid hmac-hash ?

### ISSUE THREAD

**Issue by randomuser00** [jeanpaulrichter/nppcrypt#8]
Hello,

i have a big problem, i have a file with the passwords of all my accounts including keys to unlock bitcoins and others crypto, and i'm very worried because there is alot of money in it and i can't unlock the file after that i have upgraded :s
here what i was using : 

-old version of notepadplusplus (maybe 6 months old) 32bits
-nppcrypt 1.0.1.3 32bits

what i have done :
-uninstalled notepadplusplus and settings cleared
-installed notepadplusplus 64bits latest version
-nppcrypt 1.0.1.5 x64 64bits 

i remember that i was using a custom "key preset", it have been reseted as well, i don't have this code (the value)

when i open the file and trie to decrypt it i have a message popup "Invalid hmac-hash."

Please don't tell me that i can't decrypt it because i have lost the key preset :/ :cry: :gun:

**Comment by randomuser00** [comment]
omg i have managed to restore an older version of the encrypted file which do not use custom key preset with recuva !!

i can't believe that i have managed to restore everything

lesson learned!

**Comment by jeanpaulrichter** [comment]
@randomuser00 sorry for answering this late. i just wanted to add: unlike the authentification via gcm or ccm, the hmac authentification is not needed to decrypt data. it is just an additional way to make sure the data was not tampered with (and to be honest: if you are already using gcm it is not really necessary). therefore you could just have deleted "hmac-hash", "auth-key" and "hmac" from the header and it should have decrypt just fine.

**Comment by randomuser00** [comment]
Thanks for the infos

Le 15 janv. 2018 10:45 AM, "jeanpaulrichter" <notifications@github.com> a
écrit :
